### ISSUE TITLE
What about routes converter?

### ISSUE THREAD

**Issue by ivanbarlog** [rosstuck/TuckConverterBundle#10]
It would be great if you implement similar converter for Symfony routing files.

**Comment by rosstuck** [comment]
Hi! It'd be really great but the deep, dark, terrible secret of this bundle is that it really doesn't do much of anything. Symfony already has Loaders and Dumpers for the service config and this just pipes one into the other, with a little glue in the middle.

Unfortunately, while both Loaders and Dumpers exist for the service config, only the loaders exist for the routing. So, short of writing all the dumpers, it's really not feasible at this point. It'd probably be an interesting project but I just don't have the time or energy to get them built and into Symfony core where they really ought to be (so they stay properly synced with the implementation).

Thanks for the input and using the bundle though, I really appreciate it. It's just not feasible right now. Sorry. :(
