### ISSUE TITLE
Converter son't recognize imports block 

### ISSUE THREAD

**Issue by marapper** [rosstuck/TuckConverterBundle#14]
see http://symfony.com/doc/current/cookbook/configuration/configuration_organization.html

For example

```
    <imports>
        <import resource="repositories.xml"/>
        <import resource="health_checkers.xml"/>
        <import resource="web.xml"/>
    </imports>
```

**Comment by rosstuck** [comment]
Hmm, it seems like this is a limitation of how the Symfony Loaders work and the web interface: it needs to import all of the sub files as part of the parsing process.

If you need to convert this, you can install the converter bundle in your app and then use the CLI version which seems to work on my local test. However, Symfony ends up using temp names for the different services so the output might not be what you'd expect...

Sorry, this seems to be an upstream limitation and there's no real fix I can make. It might be easier to convert the individual files containing the actual services (that should work perfectly fine) then recode this one by hand.

**Comment by marapper** [comment]
Ok. It's fine.

**Comment by rosstuck** [comment]
Sorry I couldn't be more help, thanks for reporting it though.
