### ISSUE TITLE
It would be great if it can support routing too

### ISSUE THREAD

**Issue by tom10271** [rosstuck/TuckConverterBundle#16]
As titled.

Thank you for saving me tremendous amount of time on converting XML to YAML by the way.

**Comment by rosstuck** [comment]
Hi @tom10271! I would love to be able too but Symfony doesn't have built in support for dumping routes, like it does for dumping services. Short of writing an entire sweet of dumpers by hand, I don't think that'll happen for the foreseeable future.

Sorry, though I am happy this has already helped you and thanks for letting me know! :)
